#' Calculate urban border
#'
#' This function retrieves the municipal border and land-uses from OpenStreetMaps. After it transforms the land-use polygons into points
#' every 100m^2. These points are put in the DBSCAN algorithm to cluster points. After all clusters in the largest 90% are considered urban.
#' Finally, a concave hull is drawn around the remaining urban points which represents an estimate of the urban area of interest (AOI)
#' NOTE: 
#' Literature: 
#' @param city_name character value. Name of a city
#' @param interactive TRUE or FALSE. Allows user to selct municipal borders through Mapview. This is not recommended, but can help with problems if this function returns borders for the wrong city.
#' @param historic TRUE or FALSE. Whether to retrieve current data from OpenStreetMaps or Ohsome for historic data
#' @param date character value. Which date/time to retrieve the snapshot from Ohsome
#' @param dbscan TRUE or FALSE. Use Density-based spatial clustering of applications with noise (DBSCAN) to find urban clusters.
#' @param eps Distance to be considered
#' @param minPts Minimum points for consideration of cluster
#' @param plot legacy. Can be set to TRUE
#' @keywords urban, border, DBSCAN
#' @export
#' @examples
#' PLACEHOLDER()
#' 

####################### get_urban_aoi #####################
get_urban_border_focal <- function(city_name,
                                   historic = T,
                                   date = NULL,
                                   eps = 1000, #1000m
                                   minPts = 100 #Approx 50% should be built up.
){
  
  #date to year  transformation
  dateYear <- year(as.POSIXct(date))  
  
  #Check if we already have this data downloaded
  pre_download_check_result <- pre_download_check(city_name = city_name,
                                                  object = paste0("urban_border_focal_",dateYear))
  if(is.null(pre_download_check_result)){ #if there is no file already, run the code.
    
    
    ##Find the municipal border to define the AOI
    cat("Getting municipal borders")
    municipal_aoi <- get_municipal_border(city_name,
                                          historic = T,
                                          date = date)
    municipal_aoi <- st_make_valid(municipal_aoi)
    Sys.sleep(1)
    
    ##Retrieve the LULC
    # if(historic){
    
    message("Creating Ohsome boundary")
    municipal_aoi_wip <- st_simplify(municipal_aoi, dTolerance = 0.1, preserveTopology = TRUE)
    municipal_aoi_wip <- st_make_valid(municipal_aoi_wip)
    aoi <- ohsome_boundary(municipal_aoi_wip)
    
    message("Requesting historic Ohsome data")
    query <- ohsome_elements_geometry(
      boundary = aoi,  
      filter = paste(
        "landuse=residential or",
        "landuse=commercial or",
        "landuse=construction or",
        "landuse=industrial or",
        "landuse=retail"
      ),
      time = date,
      properties = "tags",
      clipGeometry = TRUE)
    AOIretrieved <- ohsome_post(query) #Send request
    
    #fix receieved qeury
    AOI <- AOIretrieved[st_geometry_type(AOIretrieved) %in% c("POLYGON", "MULTIPOLYGON"), ]
    AOI <- st_cast(AOI, "MULTIPOLYGON")
    AOI <- st_make_valid(AOI)
    message("Retrieved historic Ohsome data for ", city_name)
    

    ##Define urban border
    #Hardcore omit bad geometry.... Shouldn've been fixed already.
    AOI <- AOI[which(st_is_valid(AOI)),]
    municipal_aoi <- municipal_aoi[which(st_is_valid(municipal_aoi)),]
    
    #Somee stuff
    AOI <- suppressWarnings(st_intersection(AOI, municipal_aoi))
    AOI <- st_make_valid(AOI)
    
    
    #Focal window
    set.seed(0)
    message("Using focal to define urban border")
    AOI <- AOI[!st_is_empty(AOI),]
    
    AOImeter <- st_transform(AOI, 3857)
    
    #Estimate cell size for raster via area of shapefile
    extentInMeters <- ext(AOImeter) # grab the extent
    xMeters <- as.numeric(abs(extentInMeters[1] - extentInMeters[2])) #x in meters
    yMeters <- as.numeric(abs(extentInMeters[3] - extentInMeters[4])) #y in meters
    
    #LULC to raster
    templateRaster <- raster(AOImeter,
                             nrows = xMeters/100, ncols = yMeters/100) #1 point per 10000m2
    raster <- fasterize(AOImeter, templateRaster)
    raster[is.na(raster)] <- 0

    
    #window 
    focalWindow <- terra::focalMat(raster, d = eps, type = "circle", fillNA = T) #make circle focal
    focalWindow[focalWindow > 0] <- 1 #count equal
    focalWindow
    
    #calc
    density <- focal(extend(rast(raster), y = nrow(raster)/10, fill = 0), w = focalWindow, fun = sum)
    dense <- density > minPts
    dense[dense == 0] <- NA #omit falses
    
    #projection fix
    dense <- project(rast(dense), municipal_aoi)
    AOIres <- mask(dense, municipal_aoi) #Remove extra area sometime generated by concave
    message("Focal delineation succesful")
    
    
    #save the urban_border
    writeRaster(AOI,
                file = paste0("MUST_downloaded_data/",city_name,"/urban_border_focal_",dateYear,".tif"),
                overwrite =T)
    
    #Return the shapefile
    return(AOI) 
  }
  else
  {
    return(pre_download_check_result)
  }
  
}
